/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.healthship.jira.client.model;

import org.junit.Test;


/**
 * Model tests for BulkCreateCustomFieldOptionRequest
 */
public class BulkCreateCustomFieldOptionRequestTest {
    private final BulkCreateCustomFieldOptionRequest model = new BulkCreateCustomFieldOptionRequest();

    /**
     * Model tests for BulkCreateCustomFieldOptionRequest
     */
    @Test
    public void testBulkCreateCustomFieldOptionRequest() {
        // TODO: test BulkCreateCustomFieldOptionRequest
    }

    /**
     * Test the property 'options'
     */
    @Test
    public void optionsTest() {
        // TODO: test options
    }

}
