/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.healthship.jira.client.model;

import org.junit.Test;


/**
 * Model tests for CreatedIssues
 */
public class CreatedIssuesTest {
    private final CreatedIssues model = new CreatedIssues();

    /**
     * Model tests for CreatedIssues
     */
    @Test
    public void testCreatedIssues() {
        // TODO: test CreatedIssues
    }

    /**
     * Test the property 'issues'
     */
    @Test
    public void issuesTest() {
        // TODO: test issues
    }

    /**
     * Test the property 'errors'
     */
    @Test
    public void errorsTest() {
        // TODO: test errors
    }

}
