/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.healthship.jira.client.model;

import org.junit.Test;


/**
 * Model tests for CustomFieldOptionValue
 */
public class CustomFieldOptionValueTest {
    private final CustomFieldOptionValue model = new CustomFieldOptionValue();

    /**
     * Model tests for CustomFieldOptionValue
     */
    @Test
    public void testCustomFieldOptionValue() {
        // TODO: test CustomFieldOptionValue
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

    /**
     * Test the property 'cascadingOptions'
     */
    @Test
    public void cascadingOptionsTest() {
        // TODO: test cascadingOptions
    }

}
