/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.healthship.jira.client.model;

import org.junit.Test;


/**
 * Model tests for CustomFieldOptionDetails
 */
public class CustomFieldOptionDetailsTest {
    private final CustomFieldOptionDetails model = new CustomFieldOptionDetails();

    /**
     * Model tests for CustomFieldOptionDetails
     */
    @Test
    public void testCustomFieldOptionDetails() {
        // TODO: test CustomFieldOptionDetails
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

    /**
     * Test the property 'cascadingOptions'
     */
    @Test
    public void cascadingOptionsTest() {
        // TODO: test cascadingOptions
    }

}
