/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.healthship.jira.client.model;

import org.junit.Test;


/**
 * Model tests for CustomFieldReplacement
 */
public class CustomFieldReplacementTest {
    private final CustomFieldReplacement model = new CustomFieldReplacement();

    /**
     * Model tests for CustomFieldReplacement
     */
    @Test
    public void testCustomFieldReplacement() {
        // TODO: test CustomFieldReplacement
    }

    /**
     * Test the property 'customFieldId'
     */
    @Test
    public void customFieldIdTest() {
        // TODO: test customFieldId
    }

    /**
     * Test the property 'moveTo'
     */
    @Test
    public void moveToTest() {
        // TODO: test moveTo
    }

}
