/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.healthship.jira.client.model;

import org.junit.Test;


/**
 * Model tests for FieldConfigurationItem
 */
public class FieldConfigurationItemTest {
    private final FieldConfigurationItem model = new FieldConfigurationItem();

    /**
     * Model tests for FieldConfigurationItem
     */
    @Test
    public void testFieldConfigurationItem() {
        // TODO: test FieldConfigurationItem
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'isHidden'
     */
    @Test
    public void isHiddenTest() {
        // TODO: test isHidden
    }

    /**
     * Test the property 'isRequired'
     */
    @Test
    public void isRequiredTest() {
        // TODO: test isRequired
    }

}
