/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.healthship.jira.client.model;

import org.junit.Test;


/**
 * Model tests for HierarchyLevel
 */
public class HierarchyLevelTest {
    private final HierarchyLevel model = new HierarchyLevel();

    /**
     * Model tests for HierarchyLevel
     */
    @Test
    public void testHierarchyLevel() {
        // TODO: test HierarchyLevel
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'aboveLevelId'
     */
    @Test
    public void aboveLevelIdTest() {
        // TODO: test aboveLevelId
    }

    /**
     * Test the property 'belowLevelId'
     */
    @Test
    public void belowLevelIdTest() {
        // TODO: test belowLevelId
    }

    /**
     * Test the property 'projectConfigurationId'
     */
    @Test
    public void projectConfigurationIdTest() {
        // TODO: test projectConfigurationId
    }

    /**
     * Test the property 'issueTypeIds'
     */
    @Test
    public void issueTypeIdsTest() {
        // TODO: test issueTypeIds
    }

    /**
     * Test the property 'externalUuid'
     */
    @Test
    public void externalUuidTest() {
        // TODO: test externalUuid
    }

}
