/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.healthship.jira.client.model;

import org.junit.Test;


/**
 * Model tests for IssueCommentListRequestBean
 */
public class IssueCommentListRequestBeanTest {
    private final IssueCommentListRequestBean model = new IssueCommentListRequestBean();

    /**
     * Model tests for IssueCommentListRequestBean
     */
    @Test
    public void testIssueCommentListRequestBean() {
        // TODO: test IssueCommentListRequestBean
    }

    /**
     * Test the property 'ids'
     */
    @Test
    public void idsTest() {
        // TODO: test ids
    }

}
