/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.healthship.jira.client.model;

import org.junit.Test;


/**
 * Model tests for IssueLinkTypes
 */
public class IssueLinkTypesTest {
    private final IssueLinkTypes model = new IssueLinkTypes();

    /**
     * Model tests for IssueLinkTypes
     */
    @Test
    public void testIssueLinkTypes() {
        // TODO: test IssueLinkTypes
    }

    /**
     * Test the property 'issueLinkTypes'
     */
    @Test
    public void issueLinkTypesTest() {
        // TODO: test issueLinkTypes
    }

}
