/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.healthship.jira.client.model;

import org.junit.Test;


/**
 * Model tests for JqlQueryClauseTimePredicate
 */
public class JqlQueryClauseTimePredicateTest {
    private final JqlQueryClauseTimePredicate model = new JqlQueryClauseTimePredicate();

    /**
     * Model tests for JqlQueryClauseTimePredicate
     */
    @Test
    public void testJqlQueryClauseTimePredicate() {
        // TODO: test JqlQueryClauseTimePredicate
    }

    /**
     * Test the property 'operator'
     */
    @Test
    public void operatorTest() {
        // TODO: test operator
    }

    /**
     * Test the property 'operand'
     */
    @Test
    public void operandTest() {
        // TODO: test operand
    }

}
