/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.healthship.jira.client.model;

import org.junit.Test;


/**
 * Model tests for Operations
 */
public class OperationsTest {
    private final Operations model = new Operations();

    /**
     * Model tests for Operations
     */
    @Test
    public void testOperations() {
        // TODO: test Operations
    }

    /**
     * Test the property 'linkGroups'
     */
    @Test
    public void linkGroupsTest() {
        // TODO: test linkGroups
    }

}
