/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.healthship.jira.client.model;

import org.junit.Test;


/**
 * Model tests for ProjectPermissions
 */
public class ProjectPermissionsTest {
    private final ProjectPermissions model = new ProjectPermissions();

    /**
     * Model tests for ProjectPermissions
     */
    @Test
    public void testProjectPermissions() {
        // TODO: test ProjectPermissions
    }

    /**
     * Test the property 'canEdit'
     */
    @Test
    public void canEditTest() {
        // TODO: test canEdit
    }

}
