/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.healthship.jira.client.model;

import org.junit.Test;


/**
 * Model tests for ProjectIssueTypeHierarchy
 */
public class ProjectIssueTypeHierarchyTest {
    private final ProjectIssueTypeHierarchy model = new ProjectIssueTypeHierarchy();

    /**
     * Model tests for ProjectIssueTypeHierarchy
     */
    @Test
    public void testProjectIssueTypeHierarchy() {
        // TODO: test ProjectIssueTypeHierarchy
    }

    /**
     * Test the property 'projectId'
     */
    @Test
    public void projectIdTest() {
        // TODO: test projectId
    }

    /**
     * Test the property 'hierarchy'
     */
    @Test
    public void hierarchyTest() {
        // TODO: test hierarchy
    }

}
