/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.healthship.jira.client.model;

import org.junit.Test;


/**
 * Model tests for PublishedWorkflowId
 */
public class PublishedWorkflowIdTest {
    private final PublishedWorkflowId model = new PublishedWorkflowId();

    /**
     * Model tests for PublishedWorkflowId
     */
    @Test
    public void testPublishedWorkflowId() {
        // TODO: test PublishedWorkflowId
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

}
