/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.healthship.jira.client.model;

import org.junit.Test;


/**
 * Model tests for RemoteIssueLinkIdentifies
 */
public class RemoteIssueLinkIdentifiesTest {
    private final RemoteIssueLinkIdentifies model = new RemoteIssueLinkIdentifies();

    /**
     * Model tests for RemoteIssueLinkIdentifies
     */
    @Test
    public void testRemoteIssueLinkIdentifies() {
        // TODO: test RemoteIssueLinkIdentifies
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'self'
     */
    @Test
    public void selfTest() {
        // TODO: test self
    }

}
