/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.healthship.jira.client.model;

import org.junit.Test;


/**
 * Model tests for RenamedCascadingOption
 */
public class RenamedCascadingOptionTest {
    private final RenamedCascadingOption model = new RenamedCascadingOption();

    /**
     * Model tests for RenamedCascadingOption
     */
    @Test
    public void testRenamedCascadingOption() {
        // TODO: test RenamedCascadingOption
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

    /**
     * Test the property 'newValue'
     */
    @Test
    public void newValueTest() {
        // TODO: test newValue
    }

}
