/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.healthship.jira.client.model;

import org.junit.Test;


/**
 * Model tests for RichText
 */
public class RichTextTest {
    private final RichText model = new RichText();

    /**
     * Model tests for RichText
     */
    @Test
    public void testRichText() {
        // TODO: test RichText
    }

    /**
     * Test the property 'emptyAdf'
     */
    @Test
    public void emptyAdfTest() {
        // TODO: test emptyAdf
    }

    /**
     * Test the property 'valueSet'
     */
    @Test
    public void valueSetTest() {
        // TODO: test valueSet
    }

}
