/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.healthship.jira.client.model;

import org.junit.Test;


/**
 * Model tests for ScreenID
 */
public class ScreenIDTest {
    private final ScreenID model = new ScreenID();

    /**
     * Model tests for ScreenID
     */
    @Test
    public void testScreenID() {
        // TODO: test ScreenID
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

}
