/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.healthship.jira.client.model;

import org.junit.Test;


/**
 * Model tests for WebhookDetails
 */
public class WebhookDetailsTest {
    private final WebhookDetails model = new WebhookDetails();

    /**
     * Model tests for WebhookDetails
     */
    @Test
    public void testWebhookDetails() {
        // TODO: test WebhookDetails
    }

    /**
     * Test the property 'jqlFilter'
     */
    @Test
    public void jqlFilterTest() {
        // TODO: test jqlFilter
    }

    /**
     * Test the property 'events'
     */
    @Test
    public void eventsTest() {
        // TODO: test events
    }

}
