/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.healthship.jira.client.api;

import org.healthship.jira.client.model.FoundGroups;
import org.healthship.jira.client.model.Group;
import org.healthship.jira.client.model.PageBeanUserDetails;
import org.junit.Ignore;
import org.junit.Test;

import java.util.List;
import java.util.Map;

/**
 * API tests for GroupsApi
 */
@Ignore
public class GroupsApiTest {

    private final GroupsApi api = new GroupsApi();

    
    /**
     * Find groups
     *
     * Returns a list of groups whose names contain a query string. A list of group names can be provided to exclude groups from the results.  The primary use case for this resource is to populate a group picker suggestions list. To this end, the returned object includes the &#x60;html&#x60; field where the matched query term is highlighted in the group name with the HTML strong tag. Also, the groups list is wrapped in a response object that contains a header for use in the picker, specifically *Showing X of Y matching groups*.  The list returns with the groups sorted. If no groups match the list criteria, an empty list is returned.  This operation can be accessed anonymously.  **[Permissions](#permissions) required:** *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg). Anonymous calls and calls by users without the required permission return an empty list.
     */
    @Test
    public void comAtlassianJiraRestV2IssueGroupPickerResourceFindGroupsGetTest()  {
        String accountId = null;
        String query = null;
        List<String> exclude = null;
        Integer maxResults = null;
        String userName = null;
        FoundGroups response = api.comAtlassianJiraRestV2IssueGroupPickerResourceFindGroupsGet(accountId, query, exclude, maxResults, userName).block();

        // TODO: test validations
    }
    
    /**
     * Add user to group
     *
     * Adds a user to a group.  **[Permissions](#permissions) required:** Site administration (that is, member of the *site-admin* [group](https://confluence.atlassian.com/x/24xjL)).
     */
    @Test
    public void comAtlassianJiraRestV2IssueGroupResourceAddUserToGroupPostTest()  {
        String groupname = null;
        Map<String, Object> requestBody = null;
        Group response = api.comAtlassianJiraRestV2IssueGroupResourceAddUserToGroupPost(groupname, requestBody).block();

        // TODO: test validations
    }
    
    /**
     * Create group
     *
     * Creates a group.  **[Permissions](#permissions) required:** Site administration (that is, member of the *site-admin* [group](https://confluence.atlassian.com/x/24xjL)).
     */
    @Test
    public void comAtlassianJiraRestV2IssueGroupResourceCreateGroupPostTest()  {
        Map<String, Object> requestBody = null;
        Group response = api.comAtlassianJiraRestV2IssueGroupResourceCreateGroupPost(requestBody).block();

        // TODO: test validations
    }
    
    /**
     * Get group
     *
     * This operation is deprecated, use [&#x60;group/member&#x60;](#api-rest-api-3-group-member-get).  Returns all users in a group.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     */
    @Test
    public void comAtlassianJiraRestV2IssueGroupResourceGetGroupGetTest()  {
        String groupname = null;
        String expand = null;
        Group response = api.comAtlassianJiraRestV2IssueGroupResourceGetGroupGet(groupname, expand).block();

        // TODO: test validations
    }
    
    /**
     * Get users from group
     *
     * Returns all users in a group.  Note that users are ordered by username, however the username is not returned in the results due to privacy reasons.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     */
    @Test
    public void comAtlassianJiraRestV2IssueGroupResourceGetUsersFromGroupGetTest()  {
        String groupname = null;
        Boolean includeInactiveUsers = null;
        Long startAt = null;
        Integer maxResults = null;
        PageBeanUserDetails response = api.comAtlassianJiraRestV2IssueGroupResourceGetUsersFromGroupGet(groupname, includeInactiveUsers, startAt, maxResults).block();

        // TODO: test validations
    }
    
    /**
     * Remove group
     *
     * Deletes a group.  **[Permissions](#permissions) required:** Site administration (that is, member of the *site-admin* strategic [group](https://confluence.atlassian.com/x/24xjL)).
     */
    @Test
    public void comAtlassianJiraRestV2IssueGroupResourceRemoveGroupDeleteTest()  {
        String groupname = null;
        String swapGroup = null;
        api.comAtlassianJiraRestV2IssueGroupResourceRemoveGroupDelete(groupname, swapGroup).block();

        // TODO: test validations
    }
    
    /**
     * Remove user from group
     *
     * Removes a user from a group.  **[Permissions](#permissions) required:** Site administration (that is, member of the *site-admin* [group](https://confluence.atlassian.com/x/24xjL)).
     */
    @Test
    public void comAtlassianJiraRestV2IssueGroupResourceRemoveUserFromGroupDeleteTest()  {
        String groupname = null;
        String accountId = null;
        String username = null;
        api.comAtlassianJiraRestV2IssueGroupResourceRemoveUserFromGroupDelete(groupname, accountId, username).block();

        // TODO: test validations
    }
    
}
