/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.healthship.jira.client.api;

import org.healthship.jira.client.model.EntityProperty;
import org.healthship.jira.client.model.PropertyKeys;
import org.junit.Ignore;
import org.junit.Test;

/**
 * API tests for IssueWorklogPropertiesApi
 */
@Ignore
public class IssueWorklogPropertiesApiTest {

    private final IssueWorklogPropertiesApi api = new IssueWorklogPropertiesApi();

    
    /**
     * Delete worklog property
     *
     * Deletes a worklog property.  This operation can be accessed anonymously.  **[Permissions](#permissions) required:**   *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.  *  If the worklog has visibility restrictions, belongs to the group or has the role visibility is restricted to.
     */
    @Test
    public void comAtlassianJiraRestV2IssueWorklogPropertyResourceDeleteWorklogPropertyDeleteTest()  {
        String issueIdOrKey = null;
        String worklogId = null;
        String propertyKey = null;
        api.comAtlassianJiraRestV2IssueWorklogPropertyResourceDeleteWorklogPropertyDelete(issueIdOrKey, worklogId, propertyKey).block();

        // TODO: test validations
    }
    
    /**
     * Get worklog property
     *
     * Returns the value of a worklog property.  This operation can be accessed anonymously.  **[Permissions](#permissions) required:**   *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.  *  If the worklog has visibility restrictions, belongs to the group or has the role visibility is restricted to.
     */
    @Test
    public void comAtlassianJiraRestV2IssueWorklogPropertyResourceGetWorklogPropertyGetTest()  {
        String issueIdOrKey = null;
        String worklogId = null;
        String propertyKey = null;
        EntityProperty response = api.comAtlassianJiraRestV2IssueWorklogPropertyResourceGetWorklogPropertyGet(issueIdOrKey, worklogId, propertyKey).block();

        // TODO: test validations
    }
    
    /**
     * Get worklog property keys
     *
     * Returns the keys of all properties for a worklog.  This operation can be accessed anonymously.  **[Permissions](#permissions) required:**   *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.  *  If the worklog has visibility restrictions, belongs to the group or has the role visibility is restricted to.
     */
    @Test
    public void comAtlassianJiraRestV2IssueWorklogPropertyResourceGetWorklogPropertyKeysGetTest()  {
        String issueIdOrKey = null;
        String worklogId = null;
        PropertyKeys response = api.comAtlassianJiraRestV2IssueWorklogPropertyResourceGetWorklogPropertyKeysGet(issueIdOrKey, worklogId).block();

        // TODO: test validations
    }
    
    /**
     * Set worklog property
     *
     * Sets the value of a worklog property. Use this operation to store custom data against the worklog.  The value of the request body must be a [valid](http://tools.ietf.org/html/rfc4627), non-empty JSON blob. The maximum length is 32768 characters.  This operation can be accessed anonymously.  **[Permissions](#permissions) required:**   *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.  *  *Edit all worklogs*[ project permission](https://confluence.atlassian.com/x/yodKLg) to update any worklog or *Edit own worklogs* to update worklogs created by the user.  *  If the worklog has visibility restrictions, belongs to the group or has the role visibility is restricted to.
     */
    @Test
    public void comAtlassianJiraRestV2IssueWorklogPropertyResourceSetWorklogPropertyPutTest()  {
        String issueIdOrKey = null;
        String worklogId = null;
        String propertyKey = null;
        Object body = null;
        Object response = api.comAtlassianJiraRestV2IssueWorklogPropertyResourceSetWorklogPropertyPut(issueIdOrKey, worklogId, propertyKey, body).block();

        // TODO: test validations
    }
    
}
