/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.healthship.jira.client.api;

import org.healthship.jira.client.model.RemoteIssueLink;
import org.healthship.jira.client.model.RemoteIssueLinkIdentifies;
import org.junit.Ignore;
import org.junit.Test;

import java.util.Map;

/**
 * API tests for IssueRemoteLinksApi
 */
@Ignore
public class IssueRemoteLinksApiTest {

    private final IssueRemoteLinksApi api = new IssueRemoteLinksApi();

    
    /**
     * Create or update remote issue link
     *
     * Creates or updates a remote issue link for an issue.  If a &#x60;globalId&#x60; is provided and a remote issue link with that global ID is found it is updated. Any fields without values in the request are set to null. Otherwise, the remote issue link is created.  This operation requires [issue linking to be active](https://confluence.atlassian.com/x/yoXKM).  This operation can be accessed anonymously.  **[Permissions](#permissions) required:**   *  *Browse projects* and *Link issues* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
     */
    @Test
    public void comAtlassianJiraRestV2IssueIssueResourceCreateOrUpdateRemoteIssueLinkPostTest()  {
        String issueIdOrKey = null;
        Map<String, Object> requestBody = null;
        RemoteIssueLinkIdentifies response = api.comAtlassianJiraRestV2IssueIssueResourceCreateOrUpdateRemoteIssueLinkPost(issueIdOrKey, requestBody).block();

        // TODO: test validations
    }
    
    /**
     * Delete remote issue link by global ID
     *
     * Deletes the remote issue link from the issue using the link&#39;s global ID. Where the global ID includes reserved URL characters these must be escaped in the request. For example, pass &#x60;system&#x3D;http://www.mycompany.com/support&amp;id&#x3D;1&#x60; as &#x60;system%3Dhttp%3A%2F%2Fwww.mycompany.com%2Fsupport%26id%3D1&#x60;.  This operation requires [issue linking to be active](https://confluence.atlassian.com/x/yoXKM).  This operation can be accessed anonymously.  **[Permissions](#permissions) required:**   *  *Browse projects* and *Link issues* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is implemented, issue-level security permission to view the issue.
     */
    @Test
    public void comAtlassianJiraRestV2IssueIssueResourceDeleteRemoteIssueLinkByGlobalIdDeleteTest()  {
        String issueIdOrKey = null;
        String globalId = null;
        api.comAtlassianJiraRestV2IssueIssueResourceDeleteRemoteIssueLinkByGlobalIdDelete(issueIdOrKey, globalId).block();

        // TODO: test validations
    }
    
    /**
     * Delete remote issue link by ID
     *
     * Deletes a remote issue link from an issue.  This operation requires [issue linking to be active](https://confluence.atlassian.com/x/yoXKM).  This operation can be accessed anonymously.  **[Permissions](#permissions) required:**   *  *Browse projects*, *Edit issues*, and *Link issues* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
     */
    @Test
    public void comAtlassianJiraRestV2IssueIssueResourceDeleteRemoteIssueLinkByIdDeleteTest()  {
        String issueIdOrKey = null;
        String linkId = null;
        api.comAtlassianJiraRestV2IssueIssueResourceDeleteRemoteIssueLinkByIdDelete(issueIdOrKey, linkId).block();

        // TODO: test validations
    }
    
    /**
     * Get remote issue link by ID
     *
     * Returns a remote issue link for an issue.  This operation requires [issue linking to be active](https://confluence.atlassian.com/x/yoXKM).  This operation can be accessed anonymously.  **[Permissions](#permissions) required:**   *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
     */
    @Test
    public void comAtlassianJiraRestV2IssueIssueResourceGetRemoteIssueLinkByIdGetTest()  {
        String issueIdOrKey = null;
        String linkId = null;
        RemoteIssueLink response = api.comAtlassianJiraRestV2IssueIssueResourceGetRemoteIssueLinkByIdGet(issueIdOrKey, linkId).block();

        // TODO: test validations
    }
    
    /**
     * Get remote issue links
     *
     * Returns the remote issue links for an issue. When a remote issue link global ID is provided the record with that global ID is returned, otherwise all remote issue links are returned. Where a global ID includes reserved URL characters these must be escaped in the request. For example, pass &#x60;system&#x3D;http://www.mycompany.com/support&amp;id&#x3D;1&#x60; as &#x60;system%3Dhttp%3A%2F%2Fwww.mycompany.com%2Fsupport%26id%3D1&#x60;.  This operation requires [issue linking to be active](https://confluence.atlassian.com/x/yoXKM).  This operation can be accessed anonymously.  **[Permissions](#permissions) required:**   *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
     */
    @Test
    public void comAtlassianJiraRestV2IssueIssueResourceGetRemoteIssueLinksGetTest()  {
        String issueIdOrKey = null;
        String globalId = null;
        RemoteIssueLink response = api.comAtlassianJiraRestV2IssueIssueResourceGetRemoteIssueLinksGet(issueIdOrKey, globalId).block();

        // TODO: test validations
    }
    
    /**
     * Update remote issue link by ID
     *
     * Updates a remote issue link for an issue.  Note: Fields without values in the request are set to null.  This operation requires [issue linking to be active](https://confluence.atlassian.com/x/yoXKM).  This operation can be accessed anonymously.  **[Permissions](#permissions) required:**   *  *Browse projects* and *Link issues* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
     */
    @Test
    public void comAtlassianJiraRestV2IssueIssueResourceUpdateRemoteIssueLinkPutTest()  {
        String issueIdOrKey = null;
        String linkId = null;
        Map<String, Object> requestBody = null;
        Object response = api.comAtlassianJiraRestV2IssueIssueResourceUpdateRemoteIssueLinkPut(issueIdOrKey, linkId, requestBody).block();

        // TODO: test validations
    }
    
}
