/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.healthship.jira.client.api;

import org.healthship.jira.client.model.IssueFieldOption;
import org.healthship.jira.client.model.PageBeanIssueFieldOption;
import org.junit.Ignore;
import org.junit.Test;

import java.util.Map;

/**
 * API tests for IssueCustomFieldOptionsAppsApi
 */
@Ignore
public class IssueCustomFieldOptionsAppsApiTest {

    private final IssueCustomFieldOptionsAppsApi api = new IssueCustomFieldOptionsAppsApi();

    
    /**
     * Create issue field option
     *
     * Creates an option for a select list issue field.  Note that this operation **only works for issue field select list options added by Connect apps**, it cannot be used with issue field select list options created in Jira or using operations from the [Issue custom field options](#api-group-Issue-custom-field-options) resource.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg). Jira permissions are not required for the app providing the field.
     */
    @Test
    public void comAtlassianJiraRestV2IssueFieldIssueFieldOptionResourceCreateIssueFieldOptionPostTest()  {
        String fieldKey = null;
        Map<String, Object> requestBody = null;
        IssueFieldOption response = api.comAtlassianJiraRestV2IssueFieldIssueFieldOptionResourceCreateIssueFieldOptionPost(fieldKey, requestBody).block();

        // TODO: test validations
    }
    
    /**
     * Delete issue field option
     *
     * Deletes an option from a select list issue field.  Note that this operation **only works for issue field select list options added by Connect apps**, it cannot be used with issue field select list options created in Jira or using operations from the [Issue custom field options](#api-group-Issue-custom-field-options) resource.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg). Jira permissions are not required for the app providing the field.
     */
    @Test
    public void comAtlassianJiraRestV2IssueFieldIssueFieldOptionResourceDeleteIssueFieldOptionDeleteTest()  {
        String fieldKey = null;
        Long optionId = null;
        Object response = api.comAtlassianJiraRestV2IssueFieldIssueFieldOptionResourceDeleteIssueFieldOptionDelete(fieldKey, optionId).block();

        // TODO: test validations
    }
    
    /**
     * Get all issue field options
     *
     * Returns all the options of a select list issue field. A select list issue field is a type of [issue field](https://developer.atlassian.com/cloud/jira/platform/modules/issue-field/) that enables a user to select a value from a list of options.  Note that this operation **only works for issue field select list options added by Connect apps**, it cannot be used with issue field select list options created in Jira or using operations from the [Issue custom field options](#api-group-Issue-custom-field-options) resource.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg). Jira permissions are not required for the app providing the field.
     */
    @Test
    public void comAtlassianJiraRestV2IssueFieldIssueFieldOptionResourceGetAllIssueFieldOptionsGetTest()  {
        String fieldKey = null;
        Long startAt = null;
        Integer maxResults = null;
        PageBeanIssueFieldOption response = api.comAtlassianJiraRestV2IssueFieldIssueFieldOptionResourceGetAllIssueFieldOptionsGet(fieldKey, startAt, maxResults).block();

        // TODO: test validations
    }
    
    /**
     * Get issue field option
     *
     * Returns an option from a select list issue field.  Note that this operation **only works for issue field select list options added by Connect apps**, it cannot be used with issue field select list options created in Jira or using operations from the [Issue custom field options](#api-group-Issue-custom-field-options) resource.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg). Jira permissions are not required for the app providing the field.
     */
    @Test
    public void comAtlassianJiraRestV2IssueFieldIssueFieldOptionResourceGetIssueFieldOptionGetTest()  {
        String fieldKey = null;
        Long optionId = null;
        IssueFieldOption response = api.comAtlassianJiraRestV2IssueFieldIssueFieldOptionResourceGetIssueFieldOptionGet(fieldKey, optionId).block();

        // TODO: test validations
    }
    
    /**
     * Get selectable issue field options
     *
     * Returns options for a select list issue field that can be viewed and selected by the user.  Note that this operation **only works for issue field select list options added by Connect apps**, it cannot be used with issue field select list options created in Jira or using operations from the [Issue custom field options](#api-group-Issue-custom-field-options) resource.  **[Permissions](#permissions) required:** Permission to access Jira.
     */
    @Test
    public void comAtlassianJiraRestV2IssueFieldIssueFieldOptionResourceGetSelectableIssueFieldOptionsGetTest()  {
        String fieldKey = null;
        Long startAt = null;
        Integer maxResults = null;
        Long projectId = null;
        PageBeanIssueFieldOption response = api.comAtlassianJiraRestV2IssueFieldIssueFieldOptionResourceGetSelectableIssueFieldOptionsGet(fieldKey, startAt, maxResults, projectId).block();

        // TODO: test validations
    }
    
    /**
     * Get visible issue field options
     *
     * Returns options for a select list issue field that can be viewed by the user.  Note that this operation **only works for issue field select list options added by Connect apps**, it cannot be used with issue field select list options created in Jira or using operations from the [Issue custom field options](#api-group-Issue-custom-field-options) resource.  **[Permissions](#permissions) required:** Permission to access Jira.
     */
    @Test
    public void comAtlassianJiraRestV2IssueFieldIssueFieldOptionResourceGetVisibleIssueFieldOptionsGetTest()  {
        String fieldKey = null;
        Long startAt = null;
        Integer maxResults = null;
        Long projectId = null;
        PageBeanIssueFieldOption response = api.comAtlassianJiraRestV2IssueFieldIssueFieldOptionResourceGetVisibleIssueFieldOptionsGet(fieldKey, startAt, maxResults, projectId).block();

        // TODO: test validations
    }
    
    /**
     * Replace issue field option
     *
     * Deselects an issue-field select-list option from all issues where it is selected. A different option can be selected to replace the deselected option. The update can also be limited to a smaller set of issues by using a JQL query.  This is an [asynchronous operation](#async). The response object contains a link to the long-running task.  Note that this operation **only works for issue field select list options added by Connect apps**, it cannot be used with issue field select list options created in Jira or using operations from the [Issue custom field options](#api-group-Issue-custom-field-options) resource.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg). Jira permissions are not required for the app providing the field.
     */
    @Test
    public void comAtlassianJiraRestV2IssueFieldIssueFieldOptionResourceReplaceIssueFieldOptionDeleteTest()  {
        String fieldKey = null;
        Long optionId = null;
        Long replaceWith = null;
        String jql = null;
        api.comAtlassianJiraRestV2IssueFieldIssueFieldOptionResourceReplaceIssueFieldOptionDelete(fieldKey, optionId, replaceWith, jql).block();

        // TODO: test validations
    }
    
    /**
     * Update issue field option
     *
     * Updates or creates an option for a select list issue field. This operation requires that the option ID is provided when creating an option, therefore, the option ID needs to be specified as a path and body parameter. The option ID provided in the path and body must be identical.  Note that this operation **only works for issue field select list options added by Connect apps**, it cannot be used with issue field select list options created in Jira or using operations from the [Issue custom field options](#api-group-Issue-custom-field-options) resource.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg). Jira permissions are not required for the app providing the field.
     */
    @Test
    public void comAtlassianJiraRestV2IssueFieldIssueFieldOptionResourceUpdateIssueFieldOptionPutTest()  {
        String fieldKey = null;
        Long optionId = null;
        IssueFieldOption issueFieldOption = null;
        IssueFieldOption response = api.comAtlassianJiraRestV2IssueFieldIssueFieldOptionResourceUpdateIssueFieldOptionPut(fieldKey, optionId, issueFieldOption).block();

        // TODO: test validations
    }
    
}
