/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.healthship.jira.client.api;

import org.healthship.jira.client.model.Component;
import org.healthship.jira.client.model.ComponentIssuesCount;
import org.healthship.jira.client.model.PageBeanComponentWithIssueCount;
import org.junit.Ignore;
import org.junit.Test;

import java.util.List;

/**
 * API tests for ProjectComponentsApi
 */
@Ignore
public class ProjectComponentsApiTest {

    private final ProjectComponentsApi api = new ProjectComponentsApi();

    
    /**
     * Create component
     *
     * Creates a component. Use components to provide containers for issues within a project.  This operation can be accessed anonymously.  **[Permissions](#permissions) required:** *Administer projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project in which the component is created or *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     */
    @Test
    public void comAtlassianJiraRestV2IssueComponentResourceCreateComponentPostTest()  {
        Component component = null;
        Component response = api.comAtlassianJiraRestV2IssueComponentResourceCreateComponentPost(component).block();

        // TODO: test validations
    }
    
    /**
     * Delete component
     *
     * Deletes a component.  This operation can be accessed anonymously.  **[Permissions](#permissions) required:** *Administer projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project containing the component or *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     */
    @Test
    public void comAtlassianJiraRestV2IssueComponentResourceDeleteComponentDeleteTest()  {
        String id = null;
        String moveIssuesTo = null;
        api.comAtlassianJiraRestV2IssueComponentResourceDeleteComponentDelete(id, moveIssuesTo).block();

        // TODO: test validations
    }
    
    /**
     * Get component
     *
     * Returns a component.  This operation can be accessed anonymously.  **[Permissions](#permissions) required:** *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for project containing the component.
     */
    @Test
    public void comAtlassianJiraRestV2IssueComponentResourceGetComponentGetTest()  {
        String id = null;
        Component response = api.comAtlassianJiraRestV2IssueComponentResourceGetComponentGet(id).block();

        // TODO: test validations
    }
    
    /**
     * Get component issues count
     *
     * Returns the counts of issues assigned to the component.  This operation can be accessed anonymously.  **[Permissions](#permissions) required:** None.
     */
    @Test
    public void comAtlassianJiraRestV2IssueComponentResourceGetComponentRelatedIssuesGetTest()  {
        String id = null;
        ComponentIssuesCount response = api.comAtlassianJiraRestV2IssueComponentResourceGetComponentRelatedIssuesGet(id).block();

        // TODO: test validations
    }
    
    /**
     * Update component
     *
     * Updates a component. Any fields included in the request are overwritten. If &#x60;leadAccountId&#x60; is an empty string (\&quot;\&quot;) the component lead is removed.  This operation can be accessed anonymously.  **[Permissions](#permissions) required:** *Administer projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project containing the component or *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     */
    @Test
    public void comAtlassianJiraRestV2IssueComponentResourceUpdateComponentPutTest()  {
        String id = null;
        Component component = null;
        Component response = api.comAtlassianJiraRestV2IssueComponentResourceUpdateComponentPut(id, component).block();

        // TODO: test validations
    }
    
    /**
     * Get project components
     *
     * Returns all components in a project. See the [Get project components paginated](#api-rest-api-3-project-projectIdOrKey-component-get) resource if you want to get a full list of components with pagination.  This operation can be accessed anonymously.  **[Permissions](#permissions) required:** *Browse Projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project.
     */
    @Test
    public void comAtlassianJiraRestV2IssueProjectResourceGetProjectComponentsGetTest()  {
        String projectIdOrKey = null;
        List<Component> response = api.comAtlassianJiraRestV2IssueProjectResourceGetProjectComponentsGet(projectIdOrKey).collectList().block();

        // TODO: test validations
    }
    
    /**
     * Get project components paginated
     *
     * Returns a [paginated](#pagination) representation of all components in a project. See the [Get project components](#api-rest-api-3-project-projectIdOrKey-components-get) resource if you want to get a full list of versions without pagination.  This operation can be accessed anonymously.  **[Permissions](#permissions) required:** *Browse Projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project.
     */
    @Test
    public void comAtlassianJiraRestV2IssueProjectResourceGetProjectComponentsPaginatedGetTest()  {
        String projectIdOrKey = null;
        Long startAt = null;
        Integer maxResults = null;
        String orderBy = null;
        String query = null;
        PageBeanComponentWithIssueCount response = api.comAtlassianJiraRestV2IssueProjectResourceGetProjectComponentsPaginatedGet(projectIdOrKey, startAt, maxResults, orderBy, query).block();

        // TODO: test validations
    }
    
}
