/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.healthship.jira.client.api;

import org.healthship.jira.client.model.ProjectType;
import org.junit.Ignore;
import org.junit.Test;

import java.util.List;

/**
 * API tests for ProjectTypesApi
 */
@Ignore
public class ProjectTypesApiTest {

    private final ProjectTypesApi api = new ProjectTypesApi();

    
    /**
     * Get accessible project type by key
     *
     * Returns a [project type](https://confluence.atlassian.com/x/Var1Nw) if it is accessible to the user.  **[Permissions](#permissions) required:** Permission to access Jira.
     */
    @Test
    public void comAtlassianJiraRestV2ProjectTypeProjectTypeResourceGetAccessibleProjectTypeByKeyGetTest()  {
        String projectTypeKey = null;
        ProjectType response = api.comAtlassianJiraRestV2ProjectTypeProjectTypeResourceGetAccessibleProjectTypeByKeyGet(projectTypeKey).block();

        // TODO: test validations
    }
    
    /**
     * Get licensed project types
     *
     * Returns all [project types](https://confluence.atlassian.com/x/Var1Nw) with a valid license.
     */
    @Test
    public void comAtlassianJiraRestV2ProjectTypeProjectTypeResourceGetAllAccessibleProjectTypesGetTest()  {
        List<ProjectType> response = api.comAtlassianJiraRestV2ProjectTypeProjectTypeResourceGetAllAccessibleProjectTypesGet().collectList().block();

        // TODO: test validations
    }
    
    /**
     * Get all project types
     *
     * Returns all [project types](https://confluence.atlassian.com/x/Var1Nw), whether or not the instance has a valid license for each type.  This operation can be accessed anonymously.  **[Permissions](#permissions) required:** None.
     */
    @Test
    public void comAtlassianJiraRestV2ProjectTypeProjectTypeResourceGetAllProjectTypesGetTest()  {
        List<ProjectType> response = api.comAtlassianJiraRestV2ProjectTypeProjectTypeResourceGetAllProjectTypesGet().collectList().block();

        // TODO: test validations
    }
    
    /**
     * Get project type by key
     *
     * Returns a [project type](https://confluence.atlassian.com/x/Var1Nw).  This operation can be accessed anonymously.  **[Permissions](#permissions) required:** None.
     */
    @Test
    public void comAtlassianJiraRestV2ProjectTypeProjectTypeResourceGetProjectTypeByKeyGetTest()  {
        String projectTypeKey = null;
        ProjectType response = api.comAtlassianJiraRestV2ProjectTypeProjectTypeResourceGetProjectTypeByKeyGet(projectTypeKey).block();

        // TODO: test validations
    }
    
}
