/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.healthship.jira.client.api;

import org.healthship.jira.client.model.*;
import org.junit.Ignore;
import org.junit.Test;

/**
 * API tests for WebhooksApi
 */
@Ignore
public class WebhooksApiTest {

    private final WebhooksApi api = new WebhooksApi();

    
    /**
     * Delete webhooks by ID
     *
     * Removes webhooks by ID. Only webhooks registered by the calling Connect app are removed. If webhooks created by other apps are specified, they are ignored.  **[Permissions](#permissions) required:** Only [Connect apps](https://developer.atlassian.com/cloud/jira/platform/integrating-with-jira-cloud/#atlassian-connect) can use this operation.
     */
    @Test
    public void comAtlassianJiraRestV2WebhookDynamicWebhookResourceDeleteWebhookByIdDeleteTest()  {
        ContainerForWebhookIDs containerForWebhookIDs = null;
        api.comAtlassianJiraRestV2WebhookDynamicWebhookResourceDeleteWebhookByIdDelete(containerForWebhookIDs).block();

        // TODO: test validations
    }
    
    /**
     * Get dynamic webhooks for app
     *
     * Returns the webhooks registered by the calling app.  **[Permissions](#permissions) required:** Only [Connect apps](https://developer.atlassian.com/cloud/jira/platform/integrating-with-jira-cloud/#atlassian-connect) can use this operation.
     */
    @Test
    public void comAtlassianJiraRestV2WebhookDynamicWebhookResourceGetDynamicWebhooksForAppGetTest()  {
        Long startAt = null;
        Integer maxResults = null;
        PageBeanWebhook response = api.comAtlassianJiraRestV2WebhookDynamicWebhookResourceGetDynamicWebhooksForAppGet(startAt, maxResults).block();

        // TODO: test validations
    }
    
    /**
     * Extend webhook life
     *
     * Webhooks registered through the REST API expire after 30 days. Call this resource periodically to keep them alive.  Unrecognized webhook IDs (nonexistent or belonging to other apps) are ignored.  **[Permissions](#permissions) required:** Only [Connect apps](https://developer.atlassian.com/cloud/jira/platform/integrating-with-jira-cloud/#atlassian-connect) can use this operation.
     */
    @Test
    public void comAtlassianJiraRestV2WebhookDynamicWebhookResourceRefreshWebhooksPutTest()  {
        ContainerForWebhookIDs containerForWebhookIDs = null;
        WebhooksExpirationDate response = api.comAtlassianJiraRestV2WebhookDynamicWebhookResourceRefreshWebhooksPut(containerForWebhookIDs).block();

        // TODO: test validations
    }
    
    /**
     * Register dynamic webhooks
     *
     * Registers webhooks.  **[Permissions](#permissions) required:** Only [Connect apps](https://developer.atlassian.com/cloud/jira/platform/integrating-with-jira-cloud/#atlassian-connect) can use this operation.
     */
    @Test
    public void comAtlassianJiraRestV2WebhookDynamicWebhookResourceRegisterDynamicWebhooksPostTest()  {
        WebhookRegistrationDetails webhookRegistrationDetails = null;
        ContainerForRegisteredWebhooks response = api.comAtlassianJiraRestV2WebhookDynamicWebhookResourceRegisterDynamicWebhooksPost(webhookRegistrationDetails).block();

        // TODO: test validations
    }
    
    /**
     * Get failed webhooks
     *
     * Returns webhooks that have recently failed to be delivered to the requesting app after the maximum number of retries.  After 72 hours the failure may no longer be returned by this operation.  The oldest failure is returned first.  This method uses a cursor-based pagination. To request the next page use the failure time of the last webhook on the list as the &#x60;failedAfter&#x60; value or use the URL provided in &#x60;next&#x60;.  **[Permissions](#permissions) required:** Only [Connect apps](https://developer.atlassian.com/cloud/jira/platform/integrating-with-jira-cloud/#atlassian-connect) can use this operation.
     */
    @Test
    public void comAtlassianJiraRestV2WebhookFailedWebhookResourceGetFailedWebhooksGetTest()  {
        Integer maxResults = null;
        Long after = null;
        FailedWebhooks response = api.comAtlassianJiraRestV2WebhookFailedWebhookResourceGetFailedWebhooksGet(maxResults, after).block();

        // TODO: test validations
    }
    
}
