/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.healthship.jira.client.api;

import org.healthship.jira.client.model.ContainerOfWorkflowSchemeAssociations;
import org.junit.Ignore;
import org.junit.Test;

import java.util.List;

/**
 * API tests for WorkflowSchemeProjectAssociationsApi
 */
@Ignore
public class WorkflowSchemeProjectAssociationsApiTest {

    private final WorkflowSchemeProjectAssociationsApi api = new WorkflowSchemeProjectAssociationsApi();

    
    /**
     * Get workflow scheme project associations
     *
     * Returns a list of the workflow schemes associated with a list of projects. Each returned workflow scheme includes a list of the requested projects associated with it. Any next-gen or non-existent projects in the request are ignored and no errors are returned.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     */
    @Test
    public void comAtlassianJiraRestV2AdminWorkflowschemeProjectWorkflowSchemeProjectResourceGetWorkflowSchemeProjectAssociationsGetTest()  {
        List<Long> projectId = null;
        ContainerOfWorkflowSchemeAssociations response = api.comAtlassianJiraRestV2AdminWorkflowschemeProjectWorkflowSchemeProjectResourceGetWorkflowSchemeProjectAssociationsGet(projectId).block();

        // TODO: test validations
    }
    
}
