/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.healthship.jira.client.api;

import org.healthship.jira.client.model.StatusDetails;
import org.junit.Ignore;
import org.junit.Test;

import java.util.List;

/**
 * API tests for WorkflowStatusesApi
 */
@Ignore
public class WorkflowStatusesApiTest {

    private final WorkflowStatusesApi api = new WorkflowStatusesApi();

    
    /**
     * Get status
     *
     * Returns a status. The status must be associated with a workflow to be returned.  If a name is used on more than one status, only the status found first is returned. Therefore, identifying the status by its ID may be preferable.  This operation can be accessed anonymously.  [Permissions](#permissions) required: None.
     */
    @Test
    public void comAtlassianJiraRestV2IssueStatusResourceGetStatusGetTest()  {
        String idOrName = null;
        StatusDetails response = api.comAtlassianJiraRestV2IssueStatusResourceGetStatusGet(idOrName).block();

        // TODO: test validations
    }
    
    /**
     * Get all statuses
     *
     * Returns a list of all statuses associated with workflows.  This operation can be accessed anonymously.  **[Permissions](#permissions) required:** None.
     */
    @Test
    public void comAtlassianJiraRestV2IssueStatusResourceGetStatusesGetTest()  {
        List<StatusDetails> response = api.comAtlassianJiraRestV2IssueStatusResourceGetStatusesGet().collectList().block();

        // TODO: test validations
    }
    
}
