/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.healthship.jira.client.api;

import org.healthship.jira.client.model.PageBeanWorkflowTransitionRules;
import org.healthship.jira.client.model.WorkflowTransitionRulesUpdate;
import org.healthship.jira.client.model.WorkflowTransitionRulesUpdateErrors;
import org.junit.Ignore;
import org.junit.Test;

import java.util.List;

/**
 * API tests for WorkflowTransitionRulesApi
 */
@Ignore
public class WorkflowTransitionRulesApiTest {

    private final WorkflowTransitionRulesApi api = new WorkflowTransitionRulesApi();

    
    /**
     * Get workflow transition rule configurations
     *
     * Returns a paginated list of workflows with transition rules. The workflows can be filtered to return only those containing workflow transition rules:   *  of one or more transition rule types, such as [workflow post functions](https://developer.atlassian.com/cloud/jira/platform/modules/workflow-post-function/).  *  matching one or more transition rule keys.  Only workflows containing transition rules created by the calling Connect app are returned. However, if a workflow is returned all transition rules that match the filters are returned for that workflow.  Due to server-side optimizations, workflows with an empty list of rules may be returned; these workflows can be ignored.  **[Permissions](#permissions) required:** Only Connect apps can use this operation.
     */
    @Test
    public void comAtlassianJiraRestV2AdminWorkflowWorkflowRuleConfigResourceGetWorkflowTransitionRuleConfigurationsGetTest()  {
        List<String> types = null;
        Long startAt = null;
        Integer maxResults = null;
        List<String> keys = null;
        String expand = null;
        PageBeanWorkflowTransitionRules response = api.comAtlassianJiraRestV2AdminWorkflowWorkflowRuleConfigResourceGetWorkflowTransitionRuleConfigurationsGet(types, startAt, maxResults, keys, expand).block();

        // TODO: test validations
    }
    
    /**
     * Update workflow transition rule configurations
     *
     * Updates configuration of workflow transition rules. The following rule types are supported:   *  [post functions](https://developer.atlassian.com/cloud/jira/platform/modules/workflow-post-function/)  *  [conditions](https://developer.atlassian.com/cloud/jira/platform/modules/workflow-condition/)  *  [validators](https://developer.atlassian.com/cloud/jira/platform/modules/workflow-validator/)  Only rules created by the calling Connect app can be updated.  **[Permissions](#permissions) required:** Only Connect apps can use this operation.
     */
    @Test
    public void comAtlassianJiraRestV2AdminWorkflowWorkflowRuleConfigResourceUpdateWorkflowTransitionRuleConfigurationsPutTest()  {
        WorkflowTransitionRulesUpdate workflowTransitionRulesUpdate = null;
        WorkflowTransitionRulesUpdateErrors response = api.comAtlassianJiraRestV2AdminWorkflowWorkflowRuleConfigResourceUpdateWorkflowTransitionRuleConfigurationsPut(workflowTransitionRulesUpdate).block();

        // TODO: test validations
    }
    
}
