/*
 * Copyright (c) 2020 Ronald MacDonald <ronald@rmacd.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 *
 * You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.healthship.jira.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Lists of JQL reference data.
 */
@ApiModel(description = "Lists of JQL reference data.")
@JsonPropertyOrder({
  JQLReferenceData.JSON_PROPERTY_VISIBLE_FIELD_NAMES,
  JQLReferenceData.JSON_PROPERTY_VISIBLE_FUNCTION_NAMES,
  JQLReferenceData.JSON_PROPERTY_JQL_RESERVED_WORDS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-03-29T15:40:13.931673+01:00[Europe/London]")
public class JQLReferenceData {
  public static final String JSON_PROPERTY_VISIBLE_FIELD_NAMES = "visibleFieldNames";
  private List<FieldReferenceData> visibleFieldNames = null;

  public static final String JSON_PROPERTY_VISIBLE_FUNCTION_NAMES = "visibleFunctionNames";
  private List<FunctionReferenceData> visibleFunctionNames = null;

  public static final String JSON_PROPERTY_JQL_RESERVED_WORDS = "jqlReservedWords";
  private List<String> jqlReservedWords = null;


  public JQLReferenceData visibleFieldNames(List<FieldReferenceData> visibleFieldNames) {
    
    this.visibleFieldNames = visibleFieldNames;
    return this;
  }

  public JQLReferenceData addVisibleFieldNamesItem(FieldReferenceData visibleFieldNamesItem) {
    if (this.visibleFieldNames == null) {
      this.visibleFieldNames = new ArrayList<>();
    }
    this.visibleFieldNames.add(visibleFieldNamesItem);
    return this;
  }

   /**
   * List of fields usable in JQL queries.
   * @return visibleFieldNames
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "List of fields usable in JQL queries.")
  @JsonProperty(JSON_PROPERTY_VISIBLE_FIELD_NAMES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<FieldReferenceData> getVisibleFieldNames() {
    return visibleFieldNames;
  }


  public void setVisibleFieldNames(List<FieldReferenceData> visibleFieldNames) {
    this.visibleFieldNames = visibleFieldNames;
  }


  public JQLReferenceData visibleFunctionNames(List<FunctionReferenceData> visibleFunctionNames) {
    
    this.visibleFunctionNames = visibleFunctionNames;
    return this;
  }

  public JQLReferenceData addVisibleFunctionNamesItem(FunctionReferenceData visibleFunctionNamesItem) {
    if (this.visibleFunctionNames == null) {
      this.visibleFunctionNames = new ArrayList<>();
    }
    this.visibleFunctionNames.add(visibleFunctionNamesItem);
    return this;
  }

   /**
   * List of functions usable in JQL queries.
   * @return visibleFunctionNames
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "List of functions usable in JQL queries.")
  @JsonProperty(JSON_PROPERTY_VISIBLE_FUNCTION_NAMES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<FunctionReferenceData> getVisibleFunctionNames() {
    return visibleFunctionNames;
  }


  public void setVisibleFunctionNames(List<FunctionReferenceData> visibleFunctionNames) {
    this.visibleFunctionNames = visibleFunctionNames;
  }


  public JQLReferenceData jqlReservedWords(List<String> jqlReservedWords) {
    
    this.jqlReservedWords = jqlReservedWords;
    return this;
  }

  public JQLReferenceData addJqlReservedWordsItem(String jqlReservedWordsItem) {
    if (this.jqlReservedWords == null) {
      this.jqlReservedWords = new ArrayList<>();
    }
    this.jqlReservedWords.add(jqlReservedWordsItem);
    return this;
  }

   /**
   * List of JQL query reserved words.
   * @return jqlReservedWords
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "List of JQL query reserved words.")
  @JsonProperty(JSON_PROPERTY_JQL_RESERVED_WORDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getJqlReservedWords() {
    return jqlReservedWords;
  }


  public void setJqlReservedWords(List<String> jqlReservedWords) {
    this.jqlReservedWords = jqlReservedWords;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JQLReferenceData jqLReferenceData = (JQLReferenceData) o;
    return Objects.equals(this.visibleFieldNames, jqLReferenceData.visibleFieldNames) &&
        Objects.equals(this.visibleFunctionNames, jqLReferenceData.visibleFunctionNames) &&
        Objects.equals(this.jqlReservedWords, jqLReferenceData.jqlReservedWords);
  }

  @Override
  public int hashCode() {
    return Objects.hash(visibleFieldNames, visibleFunctionNames, jqlReservedWords);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JQLReferenceData {\n");
    sb.append("    visibleFieldNames: ").append(toIndentedString(visibleFieldNames)).append("\n");
    sb.append("    visibleFunctionNames: ").append(toIndentedString(visibleFunctionNames)).append("\n");
    sb.append("    jqlReservedWords: ").append(toIndentedString(jqlReservedWords)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

