/*
 * Copyright (c) 2020 Ronald MacDonald <ronald@rmacd.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 *
 * You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.healthship.jira.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.time.OffsetDateTime;
import java.util.Objects;

/**
 * Additional details about a project.
 */
@ApiModel(description = "Additional details about a project.")
@JsonPropertyOrder({
  ProjectInsight.JSON_PROPERTY_TOTAL_ISSUE_COUNT,
  ProjectInsight.JSON_PROPERTY_LAST_ISSUE_UPDATE_TIME
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-03-29T15:40:13.931673+01:00[Europe/London]")
public class ProjectInsight {
  public static final String JSON_PROPERTY_TOTAL_ISSUE_COUNT = "totalIssueCount";
  private Long totalIssueCount;

  public static final String JSON_PROPERTY_LAST_ISSUE_UPDATE_TIME = "lastIssueUpdateTime";
  private OffsetDateTime lastIssueUpdateTime;


   /**
   * Total issue count.
   * @return totalIssueCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Total issue count.")
  @JsonProperty(JSON_PROPERTY_TOTAL_ISSUE_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTotalIssueCount() {
    return totalIssueCount;
  }




   /**
   * The last issue update time.
   * @return lastIssueUpdateTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The last issue update time.")
  @JsonProperty(JSON_PROPERTY_LAST_ISSUE_UPDATE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getLastIssueUpdateTime() {
    return lastIssueUpdateTime;
  }




  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProjectInsight projectInsight = (ProjectInsight) o;
    return Objects.equals(this.totalIssueCount, projectInsight.totalIssueCount) &&
        Objects.equals(this.lastIssueUpdateTime, projectInsight.lastIssueUpdateTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalIssueCount, lastIssueUpdateTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProjectInsight {\n");
    sb.append("    totalIssueCount: ").append(toIndentedString(totalIssueCount)).append("\n");
    sb.append("    lastIssueUpdateTime: ").append(toIndentedString(lastIssueUpdateTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

