/*
 * Copyright (c) 2020 Ronald MacDonald <ronald@rmacd.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 *
 * You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.healthship.jira.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * RichText
 */
@JsonPropertyOrder({
  RichText.JSON_PROPERTY_EMPTY_ADF,
  RichText.JSON_PROPERTY_VALUE_SET
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-03-29T15:40:13.931673+01:00[Europe/London]")
public class RichText {
  public static final String JSON_PROPERTY_EMPTY_ADF = "emptyAdf";
  private Boolean emptyAdf;

  public static final String JSON_PROPERTY_VALUE_SET = "valueSet";
  private Boolean valueSet;


  public RichText emptyAdf(Boolean emptyAdf) {
    
    this.emptyAdf = emptyAdf;
    return this;
  }

   /**
   * Get emptyAdf
   * @return emptyAdf
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_EMPTY_ADF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getEmptyAdf() {
    return emptyAdf;
  }


  public void setEmptyAdf(Boolean emptyAdf) {
    this.emptyAdf = emptyAdf;
  }


  public RichText valueSet(Boolean valueSet) {
    
    this.valueSet = valueSet;
    return this;
  }

   /**
   * Get valueSet
   * @return valueSet
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_VALUE_SET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getValueSet() {
    return valueSet;
  }


  public void setValueSet(Boolean valueSet) {
    this.valueSet = valueSet;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RichText richText = (RichText) o;
    return Objects.equals(this.emptyAdf, richText.emptyAdf) &&
        Objects.equals(this.valueSet, richText.valueSet);
  }

  @Override
  public int hashCode() {
    return Objects.hash(emptyAdf, valueSet);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RichText {\n");
    sb.append("    emptyAdf: ").append(toIndentedString(emptyAdf)).append("\n");
    sb.append("    valueSet: ").append(toIndentedString(valueSet)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

