/*
 * Copyright (c) 2020 Ronald MacDonald <ronald@rmacd.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 *
 * You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.healthship.jira.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * List of custom fields using the version.
 */
@ApiModel(description = "List of custom fields using the version.")
@JsonPropertyOrder({
  VersionUsageInCustomField.JSON_PROPERTY_FIELD_NAME,
  VersionUsageInCustomField.JSON_PROPERTY_CUSTOM_FIELD_ID,
  VersionUsageInCustomField.JSON_PROPERTY_ISSUE_COUNT_WITH_VERSION_IN_CUSTOM_FIELD
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-03-29T15:40:13.931673+01:00[Europe/London]")
public class VersionUsageInCustomField {
  public static final String JSON_PROPERTY_FIELD_NAME = "fieldName";
  private String fieldName;

  public static final String JSON_PROPERTY_CUSTOM_FIELD_ID = "customFieldId";
  private Long customFieldId;

  public static final String JSON_PROPERTY_ISSUE_COUNT_WITH_VERSION_IN_CUSTOM_FIELD = "issueCountWithVersionInCustomField";
  private Long issueCountWithVersionInCustomField;


   /**
   * The name of the custom field.
   * @return fieldName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The name of the custom field.")
  @JsonProperty(JSON_PROPERTY_FIELD_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFieldName() {
    return fieldName;
  }




   /**
   * The ID of the custom field.
   * @return customFieldId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the custom field.")
  @JsonProperty(JSON_PROPERTY_CUSTOM_FIELD_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getCustomFieldId() {
    return customFieldId;
  }




   /**
   * Count of the issues where the custom field contains the version.
   * @return issueCountWithVersionInCustomField
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Count of the issues where the custom field contains the version.")
  @JsonProperty(JSON_PROPERTY_ISSUE_COUNT_WITH_VERSION_IN_CUSTOM_FIELD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getIssueCountWithVersionInCustomField() {
    return issueCountWithVersionInCustomField;
  }




  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VersionUsageInCustomField versionUsageInCustomField = (VersionUsageInCustomField) o;
    return Objects.equals(this.fieldName, versionUsageInCustomField.fieldName) &&
        Objects.equals(this.customFieldId, versionUsageInCustomField.customFieldId) &&
        Objects.equals(this.issueCountWithVersionInCustomField, versionUsageInCustomField.issueCountWithVersionInCustomField);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fieldName, customFieldId, issueCountWithVersionInCustomField);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VersionUsageInCustomField {\n");
    sb.append("    fieldName: ").append(toIndentedString(fieldName)).append("\n");
    sb.append("    customFieldId: ").append(toIndentedString(customFieldId)).append("\n");
    sb.append("    issueCountWithVersionInCustomField: ").append(toIndentedString(issueCountWithVersionInCustomField)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

