/*
 * Copyright (c) 2020 Ronald MacDonald <ronald@rmacd.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 *
 * You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.healthship.jira.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.HashMap;
import java.util.Objects;

/**
 * Counts of the number of issues in various statuses.
 */
@ApiModel(description = "Counts of the number of issues in various statuses.")
@JsonPropertyOrder({
  VersionIssuesStatus.JSON_PROPERTY_UNMAPPED,
  VersionIssuesStatus.JSON_PROPERTY_TO_DO,
  VersionIssuesStatus.JSON_PROPERTY_IN_PROGRESS,
  VersionIssuesStatus.JSON_PROPERTY_DONE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-03-29T15:40:13.931673+01:00[Europe/London]")
public class VersionIssuesStatus extends HashMap<String, Object> {
  public static final String JSON_PROPERTY_UNMAPPED = "unmapped";
  private Long unmapped;

  public static final String JSON_PROPERTY_TO_DO = "toDo";
  private Long toDo;

  public static final String JSON_PROPERTY_IN_PROGRESS = "inProgress";
  private Long inProgress;

  public static final String JSON_PROPERTY_DONE = "done";
  private Long done;


   /**
   * Count of issues with a status other than *to do*, *in progress*, and *done*.
   * @return unmapped
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Count of issues with a status other than *to do*, *in progress*, and *done*.")
  @JsonProperty(JSON_PROPERTY_UNMAPPED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getUnmapped() {
    return unmapped;
  }




   /**
   * Count of issues with status *to do*.
   * @return toDo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Count of issues with status *to do*.")
  @JsonProperty(JSON_PROPERTY_TO_DO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getToDo() {
    return toDo;
  }




   /**
   * Count of issues with status *in progress*.
   * @return inProgress
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Count of issues with status *in progress*.")
  @JsonProperty(JSON_PROPERTY_IN_PROGRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getInProgress() {
    return inProgress;
  }




   /**
   * Count of issues with status *done*.
   * @return done
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Count of issues with status *done*.")
  @JsonProperty(JSON_PROPERTY_DONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getDone() {
    return done;
  }




  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VersionIssuesStatus versionIssuesStatus = (VersionIssuesStatus) o;
    return Objects.equals(this.unmapped, versionIssuesStatus.unmapped) &&
        Objects.equals(this.toDo, versionIssuesStatus.toDo) &&
        Objects.equals(this.inProgress, versionIssuesStatus.inProgress) &&
        Objects.equals(this.done, versionIssuesStatus.done) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(unmapped, toDo, inProgress, done, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VersionIssuesStatus {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    unmapped: ").append(toIndentedString(unmapped)).append("\n");
    sb.append("    toDo: ").append(toIndentedString(toDo)).append("\n");
    sb.append("    inProgress: ").append(toIndentedString(inProgress)).append("\n");
    sb.append("    done: ").append(toIndentedString(done)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

